# Generated by Django 2.0.3 on 2018-04-11 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidacy',
            unique_together={('candidate', 'election')},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('election', 'voter')},
        ),
    ]
