# Generated by Django 2.0.3 on 2018-04-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterinelection',
            old_name='user',
            new_name='voter',
        ),
    ]
