# Generated by Django 2.0.3 on 2018-06-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Referendum', 'verbose_name_plural': 'Referenda'},
        ),
    ]
