# Generated by Django 2.0.3 on 2018-04-01 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0002_auto_20180401_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionaccess',
            name='user',
        ),
        migrations.AddField(
            model_name='electionaccess',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
