# Generated by Django 2.0.3 on 2018-04-02 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20180402_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterinelection',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to=settings.AUTH_USER_MODEL),
        ),
    ]
