# Generated by Django 2.0.3 on 2018-04-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20180401_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionaccess',
            name='election',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='elections.Election'),
        ),
    ]
