# Generated by Django 2.0.3 on 2018-04-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20180401_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionaccess',
            old_name='user',
            new_name='users',
        ),
    ]
